# Data exploration

This notebook explores the raw datasets.
The goal is to understand data structure, data quality issues, and inconsistencies
that informed the design of the ETL pipeline.

In [3]:
import pandas as pd
from pathlib import Path

In [4]:
BASE_DIR = Path.cwd().parent
DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"

APPOINTMENTS_PATH = RAW_DATA_DIR / "Appointments excel.xlsx"
DOCTORS_PATH = RAW_DATA_DIR / "Doctors excel.xlsx"

df_appointments = pd.read_excel(APPOINTMENTS_PATH)
df_doctors = pd.read_excel(DOCTORS_PATH)

In [5]:
df_appointments.head()

   booking_id  patient_id  doctor_id booking_date     status
0           1          10        100   10/20/2025  confirmed
1           2          11        104   10/21/2025  cancelled
2           3          12        100   10/24/2025  confirmed
3           4          13        101   10/22/2025  confirmed
4           5          14        102   10/20/2025  cancelled

In [6]:
df_doctors.head()

   doctor_id       name specialty
0        100   Dr. Karl      Vein
1        101  Dr. Muñoz      Pain

In [7]:
# Revisión básica
print("\n--- Información general ---")
print(df_appointments.info())
print("\n--- Dimensiones ---")
print(f"Filas: {df_appointments.shape[0]}, Columnas: {df_appointments.shape[1]}")
print("\n--- Nombres de columnas ---")
print(df_appointments.columns.tolist())

--- Información general ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   booking_id    9 non-null      int64
 1   patient_id    9 non-null      int64
 2   doctor_id     9 non-null      int64
 3   booking_date  9 non-null      object
 4   status        9 non-null      object
dtypes: int64(3), object(2)
memory usage: 492.0+ bytes
None

--- Dimensiones ---
Filas: 9, Columnas: 5

--- Nombres de columnas ---
['booking_id', 'patient_id', 'doctor_id', 'booking_date', 'status']

In [8]:
# Revisión básica
print("\n--- Información general ---")
print(df_doctors.info())
print("\n--- Dimensiones ---")
print(f"Filas: {df_doctors.shape[0]}, Columnas: {df_doctors.shape[1]}")
print("\n--- Nombres de columnas ---")
print(df_doctors.columns.tolist())

--- Información general ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   doctor_id  2 non-null      int64
 1   name       2 non-null      object
 2   specialty  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes
None

--- Dimensiones ---
Filas: 2, Columnas: 3

--- Nombres de columnas ---
['doctor_id', 'name', 'specialty']

In [9]:
# Estadísticas descriptivas
display(df_appointments.describe())
display(df_appointments.describe(include='object'))

       booking_id  patient_id   doctor_id
count    9.000000    9.000000    9.000000
mean     5.000000   14.000000  102.222222
std      2.738613    2.738613    1.855921
min      1.000000   10.000000  100.000000
25%      3.000000   12.000000  101.000000
50%      5.000000   14.000000  102.000000
75%      7.000000   16.000000  104.000000
max      9.000000   18.000000  105.000000

       booking_date     status
count             9          9
unique            6          2
top      10/20/2025  confirmed
freq              3          6

In [10]:
# Estadísticas descriptivas
display(df_doctors.describe())
display(df_doctors.describe(include='object'))

        doctor_id
count    2.000000
mean   100.500000
std      0.707107
min    100.000000
25%    100.250000
50%    100.500000
75%    100.750000
max    101.000000

            name specialty
count          2         2
unique         2         2
top     Dr. Karl      Vein
freq           1         1

In [11]:
# Valores nulos y duplicados
print("\n--- Valores nulos ---")
print(df_appointments.isnull().sum())
print("\n--- Duplicados ---")
print(df_appointments.duplicated().sum())

--- Valores nulos ---
booking_id      0
patient_id      0
doctor_id       0
booking_date    0
status          0
dtype: int64

--- Duplicados ---
0

In [12]:
# Valores nulos y duplicados
print("\n--- Valores nulos ---")
print(df_doctors.isnull().sum())
print("\n--- Duplicados ---")
print(df_doctors.duplicated().sum())

--- Valores nulos ---
doctor_id    0
name         0
specialty    0
dtype: int64

--- Duplicados ---
0

In [13]:
print("\n--- valores unicos por columna ---")
print(df_appointments.nunique())

--- valores unicos por columna ---
booking_id      9
patient_id      9
doctor_id       6
booking_date    6
status          2
dtype: int64

In [14]:
print("\n--- valores unicos por columna ---")
print(df_doctors.nunique())

--- valores unicos por columna ---
doctor_id    2
name         2
specialty    2
dtype: int64

In [15]:

set(df_appointments['doctor_id'].dropna().astype(int)) - set(df_doctors['doctor_id'])

{102, 103, 104, 105}

In [16]:
df_appointments['status'].value_counts()

status
confirmed    6
cancelled    3
Name: count, dtype: int64